spring:
  application.name: ccd-case-migration-tool
  config:
    import: optional:configtree:/mnt/secrets/sscs/
    jackson.serialization.write-dates-as-timestamps: 'false'
  main.web-application-type: none

logging.level:
    root: INFO
    uk.gov.hmcts.reform: INFO

feign.client.config.default:
        connectTimeout: '60000'
        readTimeout: '60000'

idam:
  api.url: ${IDAM_API_URL:http://localhost:5062}
  client:
    id: ${IDAM_CLIENT_ID:ccd_gateway}
    secret: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET:ccd_gateway_secret}
    scope: profile openid roles
    redirect_uri: ${IDAM_OAUTH2_REDIRECT_URL:http://localhost:3451/oauth2redirect}
  oauth2.user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}
  s2s-auth:
    microservice: sscs
    totp_secret: ${DATA_STORE_IDAM_KEY:AAAAAAAAAAAAAAAB}
    url: ${IDAM_S2S_URL:http://localhost:4502}

core_case_data:
  api.url: ${CCD_DATA_STORE_API_BASE_URL:http://localhost:4452}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}

migration:
  idam:
    password: ${IDAM_PASS:dummy_password}
    username: ${IDAM_USER:idam.user@email.com}
  autoArchiveOldDrafts.enabled: ${ARCHIVE_OLD_DRAFTS_ENABLED:false}
  wa.enabled: ${MIGRATION_WA_ENABLED:false}
  dwp-enhancements.enabled: ${MIGRATION_DWP_ENABLED:false}
  case-management-location.enabled: ${MIGRATION_CASE_MANAGERMENT_LOCATION_ENABLED:false}
  defaultPanelComposition:
    enabled: ${DEFAULT_PANEL_COMPOSITION_ENABLED:false}
    use-pre-fetched-case-list: ${ULR_USE_PRE_FETCHED_CASE_LIST:false}
    encoded-data-string: ${DEFAULT_PANEL_COMPOSITION_ENCODED_STRING:==dummy++encoded--string==}
    exclusion-list-encoded-string: ${DEFAULT_PANEL_COMPOSITION_EXCLUDE_ENCODED_STRING:==dummy++encoded--string==}
  updateListingReqsMissingAmendReason:
    enabled: ${UPDATE_LISTING_REQS_MISSING_AMEND_REASON:false}
    encoded-data-string: ${UPDATE_LISTING_REQS_MISSING_AMEND_REASON_ENCODED_STRING:==dummy++encoded--string==}
  waFieldsRemoval:
    enabled: ${MIGRATION_WA_FIELDS_REMOVAL_ENABLED:false}
    encoded-data-string: ${WA_FIELDS_ENCODED_DATA_STRING:==dummy++encoded--string==}
  completedHearingsOutcomes:
    enabled: ${COMPLETED_HEARINGS_OUTCOMES_ENABLED:false}
    encoded-data-string: ${COMPLETED_HEARINGS_OUTCOMES_ENCODED_DATA_STRING:==dummy++encoded--string==}
  nonListedHearingsOutcomes:
    enabled: ${NON_LISTED_HEARINGS_OUTCOMES_ENABLED:false}
    encoded-data-string: ${NON_LISTED_HEARINGS_OUTCOMES_ENCODED_DATA_STRING:==dummy++encoded--string==}
  multipleHearingsOutcomes:
    enabled: ${MULTIPLE_HEARINGS_OUTCOMES_ENABLED:false}
    encoded-data-string: ${MULTIPLE_HEARINGS_OUTCOMES_ENCODED_DATA_STRING:==dummy++encoded--string==}
  caseOutcomeGapsMigration:
    enabled: ${CASE_OUTCOME_GAPS_MIGRATION_ENABLED:false}
    encoded-data-string: ${CASE_OUTCOME_GAPS_ENCODED_DATA_STRING:==dummy++encoded--string==}
  hmctsDwpStateMigration:
    enabled: ${HMCTS_DWP_STATE_MIGRATION_ENABLED:false}
    encoded-data-string: ${HMCTS_DWP_STATE_ENCODED_DATA_STRING:==dummy++encoded--string==}
  processingVenue:
    enabled: ${VENUE_MIGRATION_ENABLED:false}
    encoded-string: ${VENUE_MIGRATION_ENCODED_STRING:==dummy++encoded--string==}
  adjournmentFlag:
    enabled: ${ADJOURNMENT_FLAG_MIGRATION_ENABLED:false}
    encoded-data-string: ${ADJOURNMENT_FLAG_MIGRATION_ENCODED_STRING:==dummy++encoded--string==}
  panelMemberCompositionMigration:
    enabled: ${PANEL_MEMBER_COMPOSITION_MIGRATION_ENABLED:false}
    encoded-data-string: ${PANEL_MEMBER_COMPOSITION_MIGRATION_ENCODED_STRING:==dummy++encoded--string==}

case-migration:
  elasticsearch.querySize: ${MIGRATION_QUERY_SIZE:10000}
  processing.limit: ${MIGRATION_CASE_LIMIT:500}
  retry.max-retries: ${CASE_MIGRATION_MAX_RETRIES:5}

location_ref:
  enabled: 'true'
  api.url: ${RD_LOCATION_REF_API_URL:http://localhost:8084}

judicial-ref.api.url: ${JUDICIAL_REF_API_URL:http://localhost:8084}
feature.elinksV2.enabled: ${ELINKS_V2_FEATURE_ENABLED:false}
hmc.url: ${HMC_API_URL:http://localhost:8084}


